[package]
name = "hcl"
version = "0.1.0"
authors = [
    "Robert Collins <robert.collins@cognite.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
pest_consume = "1.1.0"

[dev-dependencies]
indoc = "1.0"
